// Regenerates THIRD_PARTY_LICENSES.txt after dependency changes.
//
//     cargo install --locked cargo-about --features cli   # once
//     npm run licenses                                    # in mcp/
//
// Rust: cargo-about, configured by server/about.toml (allowed licenses and
// target platforms) and server/about.hbs (output layout).
// JavaScript: the MCP server's and editor's runtime dependencies, as
// `npm ls --omit=dev` lists them after `npm ci` in mcp/, with each package's
// own license file. Dev tools (vite, vitest, eslint, ...) are left out.

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..", "..");
const OUTPUT = join(ROOT, "THIRD_PARTY_LICENSES.txt");
const RULE = "#".repeat(80);

interface PackageJson {
  name: string;
  version: string;
  license?: string;
  homepage?: string;
  repository?: string | { url?: string };
}

// Line endings are normalized so the output is the same on every platform.
function lf(text: string): string {
  return text.replace(/\r\n?/g, "\n");
}

function run(command: string, args: string[], cwd: string): string {
  // npm is npm.cmd on Windows, which only runs through a shell.
  const output = execFileSync(command, args, {
    cwd,
    encoding: "utf-8",
    stdio: ["ignore", "pipe", "inherit"],
    shell: process.platform === "win32",
  });
  return lf(output);
}

function banner(title: string): string {
  return `${RULE}\n${title}\n${RULE}\n\n`;
}

/** The runtime npm packages: name, version, license, URL and license text. */
function javascriptLicenses(): string {
  const mcp = join(ROOT, "mcp");
  run("npm", ["ci", "--no-audit", "--no-fund", "--loglevel=error"], mcp);
  const paths = run("npm", ["ls", "--omit=dev", "--all", "--parseable"], mcp)
    .split(/\r?\n/)
    .filter(Boolean);
  const packages = new Map<string, { name: string; version: string; entry: string }>();
  for (const directory of paths.slice(1)) {
    // the first is the mcp package itself
    const meta = JSON.parse(readFileSync(join(directory, "package.json"), "utf-8")) as PackageJson;
    const repository = typeof meta.repository === "object" ? meta.repository.url : meta.repository;
    const url = meta.homepage || repository || "UNKNOWN";
    const files = readdirSync(directory, { withFileTypes: true })
      .filter((f) => f.isFile() && /^(LICENSE|LICENCE|COPYING)/.test(f.name.toUpperCase()))
      .map((f) => f.name)
      .sort();
    const text =
      files.map((f) => lf(readFileSync(join(directory, f), "utf-8")).trim()).join("\n") ||
      "UNKNOWN";
    packages.set(`${meta.name}@${meta.version}`, {
      name: meta.name,
      version: meta.version,
      entry: `${meta.license ?? "UNKNOWN"}\n${url}\n${text}`,
    });
  }
  const byName = (key: { name: string }) => key.name.toLowerCase();
  return [...packages.values()]
    .sort((a, b) => (byName(a) < byName(b) ? -1 : byName(a) > byName(b) ? 1 : 0))
    .map(({ name, version, entry }) => `${name}\n${version}\n${entry}\n`)
    .join("");
}

const rust = run("cargo", ["about", "generate", "--locked", "about.hbs"], join(ROOT, "server"));
writeFileSync(
  OUTPUT,
  "Third-party software used by scratchcad, generated by mcp/scripts/third-party-licenses.ts.\n\n" +
    banner("RUST DEPENDENCIES (server/), generated by cargo-about") +
    rust +
    "\n" +
    banner("JAVASCRIPT DEPENDENCIES (mcp/), from npm ls and each package's license file") +
    javascriptLicenses(),
  "utf-8",
);
console.log(`wrote ${OUTPUT}`);
