# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Regenerates THIRD_PARTY_LICENSES.txt after dependency changes.

    cargo install --locked cargo-about --features cli   # once
    uv run scripts/third_party_licenses.py

Rust: cargo-about, configured by server/about.toml (allowed licenses and
target platforms) and server/about.hbs (output layout).
JavaScript: the MCP server's and editor's runtime dependencies, as
`npm ls --omit=dev` lists them after `npm ci` in mcp/, with each package's own
license file. Dev tools (vite, vitest, eslint, ...) are left out.
"""

import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "THIRD_PARTY_LICENSES.txt"
RULE = "#" * 80


def run(*args: str, cwd: Path) -> str:
    result = subprocess.run(
        args, cwd=cwd, check=True, stdout=subprocess.PIPE, text=True, encoding="utf-8"
    )
    return result.stdout


def banner(title: str) -> str:
    return f"{RULE}\n{title}\n{RULE}\n\n"


def javascript_licenses() -> str:
    """The runtime npm packages: name, version, license, URL and license text."""
    mcp = ROOT / "mcp"
    npm = shutil.which("npm") or "npm"
    run(npm, "ci", "--no-audit", "--no-fund", "--loglevel=error", cwd=mcp)
    paths = run(npm, "ls", "--omit=dev", "--all", "--parseable", cwd=mcp).split()
    packages = {}
    for path in paths[1:]:  # the first is the mcp package itself
        directory = Path(path)
        meta = json.loads((directory / "package.json").read_text(encoding="utf-8"))
        repository = meta.get("repository")
        if isinstance(repository, dict):
            repository = repository.get("url")
        url = meta.get("homepage") or repository or "UNKNOWN"
        files = sorted(
            f for f in directory.iterdir()
            if f.is_file() and f.name.upper().startswith(("LICENSE", "LICENCE", "COPYING"))
        )  # fmt: skip
        text = "\n".join(f.read_text(encoding="utf-8").strip() for f in files) or "UNKNOWN"
        packages[(meta["name"], meta["version"])] = (meta.get("license", "UNKNOWN"), url, text)
    return "".join(
        f"{name}\n{version}\n{license}\n{url}\n{text}\n"
        for (name, version), (license, url, text) in sorted(
            packages.items(), key=lambda item: item[0][0].lower()
        )
    )


def main() -> None:
    rust = run("cargo", "about", "generate", "--locked", "about.hbs", cwd=ROOT / "server")
    OUTPUT.write_text(
        "Third-party software used by scratchcad, generated by scripts/third_party_licenses.py.\n\n"
        + banner("RUST DEPENDENCIES (server/), generated by cargo-about")
        + rust
        + "\n"
        + banner("JAVASCRIPT DEPENDENCIES (mcp/), from npm ls and each package's license file")
        + javascript_licenses(),
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
