#!/usr/bin/env bash
# Regenerates THIRD_PARTY_LICENSES.txt from the lockfiles. Run it from
# anywhere after changing dependencies:
#
#   cargo install --locked cargo-about --features cli   # once
#   scripts/third-party-licenses.sh
#
# The Rust section covers the `server` crate's non-dev dependencies (see
# server/about.toml); the Python section covers the MCP server's runtime
# dependencies as locked in mcp/uv.lock, with the license files each package
# ships. Development-only tools (pytest, ruff, mypy, ...) are not distributed
# and are left out.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/THIRD_PARTY_LICENSES.txt"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

(cd "$root/server" && cargo about generate --locked about.hbs -o "$tmp")

cd "$root/mcp"
uv sync --locked --quiet
requirements="$(uv export --locked --no-dev --no-hashes --no-emit-project --no-header --no-annotate)"

{
    cat <<'EOF'
THIRD-PARTY SOFTWARE NOTICES AND LICENSES

madcad is licensed under the Apache License 2.0 (see LICENSE). It depends on
the third-party software listed below, which is distributed under its own
license terms. This file is generated by scripts/third-party-licenses.sh;
do not edit it by hand.

################################################################################
PART 1: RUST DEPENDENCIES (server/)
################################################################################

EOF
    cat "$tmp"
    cat <<'EOF'

################################################################################
PART 2: PYTHON DEPENDENCIES (mcp/)
################################################################################

EOF
    uv run --no-sync python - "$requirements" <<'EOF'
import email
import io
import json
import re
import sys
import urllib.request
import zipfile
from importlib.metadata import PackageNotFoundError, distribution

from packaging.markers import Marker

# Platforms madcad's MCP server runs on: the Docker image and native installs.
ENVIRONMENTS = [
    {"sys_platform": "linux", "platform_system": "Linux"},
    {"sys_platform": "win32", "platform_system": "Windows"},
    {"sys_platform": "darwin", "platform_system": "Darwin"},
]
PYTHON = {
    "implementation_name": "cpython",
    "platform_python_implementation": "CPython",
    "python_version": "3.14",
    "python_full_version": "3.14.0",
}
# Packages whose wheels ship no license file, mapped to a package from the
# same repository and under the same license that does.
LICENSE_FROM = {"fastmcp-slim": "fastmcp"}
LICENSE_FILE = re.compile(r"(LICEN[CS]E|COPYING|NOTICE|AUTHORS)", re.IGNORECASE)


def wanted(marker: str) -> bool:
    return not marker or any(Marker(marker).evaluate({**PYTHON, **env}) for env in ENVIRONMENTS)


def installed(name: str) -> tuple[email.message.Message, list[tuple[str, str]]]:
    dist = distribution(name)
    files = [
        (f.name, f.read_text(encoding="utf-8"))
        for f in sorted(dist.files or [])
        if ".dist-info/" in str(f) and LICENSE_FILE.search(f.name)
    ]
    return dist.metadata, files


def from_pypi(name: str, version: str) -> tuple[email.message.Message, list[tuple[str, str]]]:
    """Reads a package that isn't installed here (e.g. Windows-only) from its wheel."""
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json") as r:
        wheels = [u for u in json.load(r)["urls"] if u["packagetype"] == "bdist_wheel"]
    with urllib.request.urlopen(wheels[0]["url"]) as r:
        wheel = zipfile.ZipFile(io.BytesIO(r.read()))
    info = [n for n in wheel.namelist() if n.split("/")[0].endswith(".dist-info")]
    meta = email.message_from_bytes(wheel.read(next(n for n in info if n.endswith("/METADATA"))))
    files = [
        (n.rsplit("/", 1)[1], wheel.read(n).decode("utf-8"))
        for n in sorted(info)
        if LICENSE_FILE.search(n.rsplit("/", 1)[1])
    ]
    return meta, files


def load(name: str, version: str) -> tuple[email.message.Message, list[tuple[str, str]]]:
    try:
        return installed(name)
    except PackageNotFoundError:
        return from_pypi(name, version)


requirements = []
for line in sys.argv[1].splitlines():
    if not line or line.startswith(("#", "-")):
        continue
    spec, _, marker = line.partition(";")
    name, _, version = spec.strip().partition("==")
    if wanted(marker.strip()):
        requirements.append((name, version, marker.strip()))

for name, version, marker in sorted(requirements, key=lambda r: r[0].lower()):
    meta, files = load(name, version)
    source = LICENSE_FROM.get(name.lower())
    if source:
        files = load(source, version)[1]
    if not files:
        sys.exit(f"{name} ships no license file; map it in LICENSE_FROM or add its text here")

    license_name = meta.get("License-Expression") or meta.get("License") or ""
    if not license_name or "\n" in license_name:
        classifiers = [
            c.split(" :: ")[-1] for c in meta.get_all("Classifier") or [] if c.startswith("License ::")
        ]
        license_name = " OR ".join(classifiers) or "see license text below"
    urls = dict(u.split(", ", 1) for u in meta.get_all("Project-URL") or [] if ", " in u)
    url = urls.get("Source") or urls.get("Repository") or urls.get("Homepage") or meta.get("Home-page")

    print("=" * 80)
    print(f"{meta['Name']} {version}")
    print(f"License: {license_name}")
    if url:
        print(f"URL: {url}")
    if marker:
        print(f"Only when: {marker}")
    print("-" * 80)
    if source:
        print(f"(license text from {source}, published from the same repository)")
    for filename, text in files:
        if len(files) > 1:
            print(f"[{filename}]")
        print(text.strip())
        print()
EOF
} > "$out"

echo "wrote $out"
