#!/usr/bin/env bash
# Regenerates THIRD_PARTY_LICENSES.txt after dependency changes:
#
#   cargo install --locked cargo-about --features cli   # once
#   scripts/third-party-licenses.sh
#
# Rust: cargo-about, configured by server/about.toml (allowed licenses and
# target platforms) and server/about.hbs (output layout).
# Python: pip-licenses, run against a fresh environment holding only the MCP
# server's runtime dependencies, so dev tools (pytest, ruff, ...) are left out.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
venv="$(mktemp -d)"
rule="$(printf "%.0s#" {1..80})"
trap 'rm -rf "$venv"' EXIT

(cd "$root/mcp" && UV_PROJECT_ENVIRONMENT="$venv" uv sync --locked --no-dev --no-install-project --quiet)

{
    printf 'Third-party software used by madcad, generated by scripts/third-party-licenses.sh.\n\n'
    printf '%s\nRUST DEPENDENCIES (server/), generated by cargo-about\n%s\n\n' "$rule" "$rule"
    (cd "$root/server" && cargo about generate --locked about.hbs)
    printf '\n%s\nPYTHON DEPENDENCIES (mcp/), generated by pip-licenses\n%s\n\n' "$rule" "$rule"
    uvx pip-licenses==5.5.5 --python "$venv/bin/python" --format=plain-vertical \
        --with-urls --with-license-file --no-license-path
} > "$root/THIRD_PARTY_LICENSES.txt"

echo "wrote $root/THIRD_PARTY_LICENSES.txt"
