# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Regenerates THIRD_PARTY_LICENSES.txt after dependency changes.

    cargo install --locked cargo-about --features cli   # once
    uv run scripts/third_party_licenses.py

Rust: cargo-about, configured by server/about.toml (allowed licenses and
target platforms) and server/about.hbs (output layout).
Python: pip-licenses, run against a fresh environment holding only the MCP
server's runtime dependencies, so dev tools (pytest, ruff, ...) are left out.
"""

import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "THIRD_PARTY_LICENSES.txt"
PIP_LICENSES = "pip-licenses==5.5.5"
RULE = "#" * 80


def run(*args: str, cwd: Path, env: dict[str, str] | None = None) -> str:
    result = subprocess.run(
        args, cwd=cwd, env=env, check=True, stdout=subprocess.PIPE, text=True, encoding="utf-8"
    )
    return result.stdout


def banner(title: str) -> str:
    return f"{RULE}\n{title}\n{RULE}\n\n"


def main() -> None:
    rust = run("cargo", "about", "generate", "--locked", "about.hbs", cwd=ROOT / "server")

    with tempfile.TemporaryDirectory() as venv:
        env = {**os.environ, "UV_PROJECT_ENVIRONMENT": venv}
        sync = ("uv", "sync", "--locked", "--no-dev", "--no-install-project", "--quiet")
        run(*sync, cwd=ROOT / "mcp", env=env)
        windows = sys.platform == "win32"
        python = str(
            Path(venv, "Scripts", "python.exe") if windows else Path(venv, "bin", "python")
        )
        python_licenses = run(
            "uvx", PIP_LICENSES, "--python", python, "--format=plain-vertical",
            "--with-urls", "--with-license-file", "--no-license-path",
            cwd=ROOT,
        )  # fmt: skip

    OUTPUT.write_text(
        "Third-party software used by scratchcad, generated by scripts/third_party_licenses.py.\n\n"
        + banner("RUST DEPENDENCIES (server/), generated by cargo-about")
        + rust
        + "\n"
        + banner("PYTHON DEPENDENCIES (mcp/), generated by pip-licenses")
        + python_licenses,
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
